## The makeMatrix function is implemented to create a specific vector, consisting of the 
## functions to set and get the value of matrix, as well as set and get the value of the 
## matrix inverse

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {               #setting the matrix value
                x <<- y
                inv <<- NULL               #initialize the value of the inverse
        }
        get <- function() x                #get the matrix value
        setinverse <- function(solve) inv <<- solve         #set the inverse value 
        getinverse <- function() inv                        #get the inverse value
        list(set = set, get = get,                          #compose the vector of 4 functions above
             setinverse = setinverse,
             getinverse = getinverse)
}


## The cachesolve takes as an input, the vector generated by makeCacheMatrix function
## It first checks whether the inverse has already been calculated for the matrix.
## If the inverse has been computed, the cached value is returned, otherwise, 
## the inverse is calculated by means of solve() function, and is stored via setinverse() function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getinverse()                    #try to get the inverse from the cache
        if(!is.null(inv)) {                      #if it exists, return the cached data
                message("getting cached data")
                return(inv)
        }
        data <- x$get()                          
        inv <- solve(data, ...)                 #calculate the inverse, if if wasnot found in the cache
        x$setinverse(inv)                       #store thr calculated inverse in cache
        inv
}
