## The makeMatrix function is implemented to create a specific vector, consisting of the 
## functions to set and get the value of matrix, as well as set and get the value of the 
## matrix inverse

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setinverse <- function(mean) inv <<- mean
        getinverse <- function() inv
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## The cachesolve takes as an input, the vector generated by makeCacheMatrix function
## It first checks whether the inverse has already been calculated for the matrix.
## If the inverse has been computed, the cached value is returned, otherwise, 
## the inverse is calculated by means of solve() function, and is stored via setinverse() function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getinverse()
        if(!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        data <- x$get()
        inv <- solve(data, ...)
        x$setinverse(inv)
        inv
}
